<?php

namespace Oxygen\Controllers;

use Oxygen\Core\Controller;
use Oxygen\Core\Request;
use Oxygen\Core\Response;
use Oxygen\Core\Validator;
use Oxygen\Core\Flash;
use Oxygen\Core\Storage;
use Oxygen\Models\Post;

/**
 * PostController
 * 
 * Generated by OxygenFramework Scaffolder
 */
class PostController extends Controller
{
    public function index()
    {
        $items = Post::paginate(15);
        
        return $this->view('posts/index', ['items' => $items]);
    }

    public function create()
    {
        return $this->view('posts/create');
    }

    public function store()
    {
        $request = $this->app->make(Request::class);
        
        // Use clean() to strip HTML tags (Security)
        $validator = Validator::make($request->clean(), [
            'title' => 'required|string|max:250',
            'content' => 'required|string',
            'status' => 'required|in:published,draft',
        ]);
        
        if ($validator->fails()) {
            Flash::error('Validation failed!');
            $_SESSION['errors'] = $validator->errors();
            $_SESSION['old'] = $request->all();
            Response::redirect('/posts/create');
            return;
        }

        $data = $validator->validated();

        // Handle File Uploads

        
        Post::create($data);
        Flash::success('Post created successfully!');
        Response::redirect('/posts');
    }

    public function show($id)
    {
        $item = Post::find($id);
        return $this->view('posts/show', ['item' => $item]);
    }

    public function edit($id)
    {
        $item = Post::find($id);
        return $this->view('posts/edit', ['item' => $item]);
    }

    public function update($id)
    {
        $request = $this->app->make(Request::class);
        
        // Use clean() to strip HTML tags (Security)
        $validator = Validator::make($request->clean(), [
            'title' => 'required|string|max:250',
            'content' => 'required|string',
            'status' => 'required|in:published,draft',
        ]);
        
        if ($validator->fails()) {
            Flash::error('Validation failed!');
            $_SESSION['errors'] = $validator->errors();
            $_SESSION['old'] = $request->all();
            Response::redirect('/posts/' . $id . '/edit');
            return;
        }

        $data = $validator->validated();

        // Handle File Uploads

        
        Post::update($id, $data);
        Flash::success('Post updated successfully!');
        Response::redirect('/posts');
    }

    public function destroy($id)
    {
        Post::delete($id);
        Flash::success('Post deleted successfully!');
        Response::redirect('/posts');
    }
}