<?php

namespace Oxygen\Controllers;

use Oxygen\Core\Controller;
use Oxygen\Core\Request;
use Oxygen\Core\Response;
use Oxygen\Core\Validator;
use Oxygen\Core\Flash;
use Oxygen\Core\Storage;
use Oxygen\Models\Poster;

/**
 * PosterController
 * 
 * Generated by OxygenFramework Scaffolder
 */
class PosterController extends Controller
{
    public function index()
    {
        $search = $_GET['search'] ?? null;

        if ($search) {
            $items = Poster::where('title', 'LIKE', "%{$search}%");
        } else {
            $items = Poster::paginate(15);
        }

        return $this->view('posters/index', ['items' => $items]);
    }

    public function create()
    {
        $userses = \Oxygen\Models\User::find(1);

        return $this->view('posters/create', ['userses' => $userses]);
    }

    public function store()
    {
        $request = $this->app->make(Request::class);

        // Use clean() to strip HTML tags (Security)
        $validator = Validator::make($request->clean(), [
            'title' => 'required|string',
            'user_id' => 'required|integer',
        ]);

        if ($validator->fails()) {
            Flash::error('Validation failed!');
            $_SESSION['errors'] = $validator->errors();
            $_SESSION['old'] = $request->all();
            Response::redirect('/posters/create');
            return;
        }

        $data = $validator->validated();

        // Handle File Uploads
        Poster::create($data);
        Flash::success('Poster created successfully!');
        Response::redirect('/posters');
    }

    public function show($id)
    {
        $item = Poster::find($id);
        return $this->view('posters/show', ['item' => $item]);
    }

    public function edit($id)
    {
        $item = Poster::find($id);
        $userses = \Oxygen\Models\User::all();
        return $this->view('posters/edit', ['item' => $item, 'userses' => $userses]);
    }

    public function update($id)
    {
        $request = $this->app->make(Request::class);

        // Use clean() to strip HTML tags (Security)
        $validator = Validator::make($request->clean(), [
            'title' => 'required|string',
            'user_id' => 'required|integer',
        ]);

        if ($validator->fails()) {
            Flash::error('Validation failed!');
            $_SESSION['errors'] = $validator->errors();
            $_SESSION['old'] = $request->all();
            Response::redirect('/posters/' . $id . '/edit');
            return;
        }

        $data = $validator->validated();

        // Handle File Uploads


        Poster::update($id, $data);
        Flash::success('Poster updated successfully!');
        Response::redirect('/posters');
    }

    public function destroy($id)
    {
        Poster::delete($id);
        Flash::success('Poster deleted successfully!');
        Response::redirect('/posters');
    }
}