<?php

namespace Oxygen\Models;

use Oxygen\Core\Model;

/**
 * Post Model
 * 
 * Generated by OxygenFramework Scaffolder
 */
class Post extends Model
{
    protected $table = 'posts';
    
    protected $fillable = [
        'title',
        'content',
        'status'
    ];

}
