<?php

namespace Oxygen\Models;

use Oxygen\Core\Model;

/**
 * Poster Model
 * 
 * Generated by OxygenFramework Scaffolder
 */
class Poster extends Model
{
    protected $table = 'posters';

    protected $fillable = [
        'title',
        'user_id'
    ];

    /**
     * belongsTo relationship
     */
    public function users()
    {
        return $this->belongsTo(User::class);
    }

}
